name: Bug report
description: Create a bug report to help us improve 
title: "[Bug]: "
labels: ["bug"]
body:
- type: markdown
  attributes:
    value: "# QuantuMiz Issue Tracker"
- type: markdown
  attributes:
    value: |
      Welcome to Issue Tracker! Here are things to remember before creating issue:
      * Please use [mc.logs](https://mclo.gs) for crash report or your full logs. Any attachment which includes sensitive information will be immediately removed.
      * Any modification of mods list (excluding your own resource packs/shader packs), including your own addition/removal of mods will be unsupported and will be immediately rejected. Please ensure nothing was changed on our list of mods.
      * We do NOT accept any issues that are from any other modpack(s), including fork/reuploads of this modpack. Make sure you are using official release of QuantuMiz/QuantuMiz CE before reporting.
- type: input
    label: Describe the bug
  attributes:
    description: "A clear and concise description of what the bug is."
  validations:
    required: true
- type: textarea
  attributes:
    label: To Reproduce
    description: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  validations:
    required: true
- type: input
  attributes:
    label: Expected behavior
    description: "A clear and concise description of what you expected to happen."
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots
    description: "If applicable, add screenshots to help explain your problem."
  validations:
    required: true
- type: input
  attributes:
    label: Type of the modpack
    placeholder: "e.g. QuantuMiz/QuantuMiz CE/QuantuMiz EX"
  validations:
    required: true
- type: input
  attributes:
    label: Operating System Name/Version
    placeholder: "e.g. Windows 11 24H2/macOS 15/Linux (Example: Ubuntu 24.04, Fedora 40)/etc."
  validations:
    required: true
- type: input
  attributes:
    label: Modpack Version
    placeholder: "e.g.: QuantuMiz 2.3.0"
  validations:
    required: true
- type: input
  attributes:
    label: Minecraft Version
    placeholder: "e.g. 1.20.6"
  validations:
    required: true
- type: input
  attributes:
    label: Name of Launcher you are using
    placeholder: "e.g. Prism Launcher/Modrinth App/ATLauncher/etc."
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: "Add any other context about the problem here."
  validations:
    required: true
