name: Feedback
description: Suggest an idea for QuantuMiz series
title: "[Feedback]: "
labels: ["enhancement"]
body:
- type: markdown
  attributes:
    value: "# QuantuMiz Issue Tracker"
- type: markdown
  attributes:
    value: |
      Welcome to Issue Tracker! Here are things to remember before creating issue:
      * Please use [mc.logs](https://mclo.gs) for crash report or your full logs. Any attachment which includes sensitive information will be immediately removed.
      * Any modification of mods list (excluding your own resource packs/shader packs), including your own addition/removal of mods will be unsupported and will be immediately rejected. Please ensure nothing was changed on our list of mods.
      * We do NOT accept any issues that are from any other modpack(s), including fork/reuploads of this modpack. Make sure you are using official release of QuantuMiz/QuantuMiz CE before reporting.
- type: input
  attributes:
    label: Which QuantuMiz edition?
    placeholder: "e.g. QuantuMiz/QuantuMiz CE/QuantuMiz EX"
  validations:
    required: true
- type: textarea
  attributes:
    label: Is your feature request related to a problem? Please describe.
    description: "A clear and concise description of what the problem is."
    placeholder: "Ex. I'm always frustrated when [...]"
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: "A clear and concise description of what you want to happen."
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe alternatives you've considered
    description: "A clear and concise description of any alternative solutions or features you've considered."
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: "Add any other context or screenshots about the feature request here."
  validations:
    required: true
